# Generated by Django 5.2.17 on 2026-09-16 17:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='Domicile', max_length=100, verbose_name='titre (ex: Domicile, Bureau)')),
                ('adresse', models.CharField(max_length=255, verbose_name='adresse complète')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='instructions pour le livreur')),
                ('est_defaut', models.BooleanField(default=False, verbose_name='adresse par défaut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_livraison', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Adresse de Livraison Client',
                'verbose_name_plural': 'Adresses de Livraison Client',
                'ordering': ['-est_defaut', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_commande', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='numéro de commande')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAYEE', 'Payée'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE_PAIEMENT', max_length=30, verbose_name='statut de la commande')),
                ('sous_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='sous-total (FCFA)')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='frais de livraison (FCFA)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total général (FCFA)')),
                ('adresse_livraison', models.CharField(max_length=255, verbose_name='adresse de livraison')),
                ('latitude_livraison', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude livraison')),
                ('longitude_livraison', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude livraison')),
                ('instructions_livraison', models.TextField(blank=True, default='', verbose_name='instructions de livraison')),
                ('nom_destinataire', models.CharField(max_length=150, verbose_name='nom du destinataire')),
                ('telephone_destinataire', models.CharField(max_length=30, verbose_name='téléphone du destinataire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_produit_snapshot', models.CharField(max_length=200, verbose_name='nom du produit (snapshot)')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire (FCFA)')),
                ('total_ligne', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total ligne (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='catalog.produit', verbose_name='produit catalogue')),
            ],
            options={
                'verbose_name': 'Ligne de Commande',
                'verbose_name_plural': 'Lignes de Commande',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_option_snapshot', models.CharField(max_length=150, verbose_name='nom option (snapshot)')),
                ('type_option_snapshot', models.CharField(default='SAUCE', max_length=20, verbose_name='type option (snapshot)')),
                ('prix_supplementaire_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='prix supplémentaire snapshot (FCFA)')),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_snapshot', to='orders.lignecommande', verbose_name='ligne de commande')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.optionproduit', verbose_name="option d'origine")),
            ],
            options={
                'verbose_name': 'Option Ligne de Commande',
                'verbose_name_plural': 'Options Lignes de Commande',
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeVariante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_variante_snapshot', models.CharField(max_length=150, verbose_name='nom variante (snapshot)')),
                ('prix_supplementaire_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='prix supplémentaire snapshot (FCFA)')),
                ('ligne_commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variante_snapshot', to='orders.lignecommande', verbose_name='ligne de commande')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.varianteproduit', verbose_name="variante d'origine")),
            ],
            options={
                'verbose_name': 'Variante Ligne de Commande',
                'verbose_name_plural': 'Variantes Lignes de Commande',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire snapshot (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('options', models.ManyToManyField(blank=True, related_name='panier_items', to='catalog.optionproduit', verbose_name='options / suppléments choisis')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.panier', verbose_name='panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier_items', to='catalog.produit', verbose_name='produit')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panier_items', to='catalog.varianteproduit', verbose_name='variante choisie')),
            ],
            options={
                'verbose_name': 'Article de Panier',
                'verbose_name_plural': 'Articles de Panier',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SousCommande',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAYEE', 'Payée'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE_PAIEMENT', max_length=30, verbose_name='statut de la sous-commande')),
                ('sous_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='sous-total établissement (FCFA)')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='frais livraison établissement (FCFA)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total établissement (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_commandes', to='orders.commande', verbose_name='commande principale')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_commandes', to='catalog.etablissement', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'Sous-Commande Établissement',
                'verbose_name_plural': 'Sous-Commandes Établissements',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='sous_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.souscommande', verbose_name='sous-commande'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['utilisateur', 'statut'], name='orders_comm_utilisa_c892c7_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['numero_commande'], name='orders_comm_numero__364ae9_idx'),
        ),
        migrations.AddConstraint(
            model_name='panier',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('utilisateur',), name='unique_panier_actif_utilisateur'),
        ),
    ]
