# Generated by Django 5.2.17 on 2026-10-02 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_etablissement_date_debut_abonnement_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepasPlanifie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_planifiee', models.DateField(db_index=True, verbose_name='date planifiée')),
                ('creneau', models.CharField(choices=[('MATIN', 'Petit-déjeuner'), ('MIDI', 'Déjeuner'), ('SOIR', 'Dîner'), ('EN_CAS', 'En-cas / Collation')], db_index=True, default='MIDI', max_length=20, verbose_name='créneau du repas')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('COMMANDE', 'Commande créée'), ('ANNULE', 'Annulé')], db_index=True, default='PLANIFIE', max_length=30, verbose_name='statut')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix total (FCFA)')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='instructions spécifiques')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas_planifies', to='catalog.etablissement', verbose_name='établissement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas_planifies', to='catalog.produit', verbose_name='produit planifié')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas_planifies', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repas_planifies', to='catalog.varianteproduit', verbose_name='variante choisie')),
            ],
            options={
                'verbose_name': 'Repas Planifié',
                'verbose_name_plural': 'Repas Planifiés',
                'ordering': ['date_planifiee', 'creneau', 'id'],
                'indexes': [models.Index(fields=['utilisateur', 'date_planifiee'], name='orders_repa_utilisa_106593_idx')],
            },
        ),
    ]
