# Generated by Django 5.2.17 on 2026-10-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_repasplanifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasplanifie',
            name='rappel_reporte',
            field=models.BooleanField(default=False, verbose_name='rappel reporté'),
        ),
        migrations.AddField(
            model_name='repasplanifie',
            name='rappel_reporte_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de report du rappel'),
        ),
        migrations.AddField(
            model_name='repasplanifie',
            name='rappel_valide',
            field=models.BooleanField(default=False, verbose_name='rappel validé'),
        ),
        migrations.AddField(
            model_name='repasplanifie',
            name='rappel_valide_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de validation du rappel'),
        ),
    ]
