# Generated by Django 5.2.17 on 2026-10-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_repasplanifie_rappel_reporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasplanifie',
            name='heure_planifiee',
            field=models.TimeField(blank=True, null=True, verbose_name='heure planifiée'),
        ),
    ]
