# Generated by Django 5.2.17 on 2026-09-16 19:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='référence interne AYYOU')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant du paiement (FCFA)')),
                ('methode', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('CARTE_BANCAIRE', 'Carte Bancaire'), ('CASH', 'Paiement à la livraison (Cash)'), ('AUTRE', 'Autre')], db_index=True, default='WAVE', max_length=30, verbose_name='méthode de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('INITIE', 'Initié'), ('PAYE', 'Payé'), ('ECHOUE', 'Échoué'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=30, verbose_name='statut du paiement')),
                ('transaction_externe', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='identifiant transaction externe')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='date de paiement effectif')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='données complémentaires')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='orders.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='numéro de facture')),
                ('nom_client_snapshot', models.CharField(max_length=150, verbose_name='nom client (snapshot)')),
                ('telephone_client_snapshot', models.CharField(max_length=30, verbose_name='téléphone client (snapshot)')),
                ('adresse_livraison_snapshot', models.TextField(verbose_name='adresse de livraison (snapshot)')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='montant hors taxes (FCFA)')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='frais de livraison (FCFA)')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant total TTC (FCFA)')),
                ('details_lignes_snapshot', models.JSONField(blank=True, default=list, verbose_name='détails des articles (snapshot)')),
                ('est_payee', models.BooleanField(default=False, verbose_name='facture acquittée')),
                ('date_emission', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date d'émission")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='date de règlement')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='orders.commande', verbose_name='commande associée')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='payments.paiement', verbose_name='paiement associé')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['commande', 'statut'], name='payments_pa_command_ae73ca_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reference'], name='payments_pa_referen_2444ed_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['numero_facture'], name='payments_fa_numero__b7a4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['est_payee'], name='payments_fa_est_pay_884f82_idx'),
        ),
    ]
