# Generated by Django 5.2.17 on 2026-09-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='numéro de facture'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='référence interne AYYOU'),
        ),
    ]
