# Generated by Django 5.2.17 on 2026-09-24 18:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_facture_numero_facture_and_more'),
        ('users', '0005_profillivreur_date_expiration_assurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant du versement (FCFA)')),
                ('methode', models.CharField(default='WAVE', max_length=50, verbose_name='méthode de retrait')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITE', 'Traité'), ('ECHOUE', 'Échoué')], db_index=True, default='EN_ATTENTE', max_length=30, verbose_name='statut du versement')),
                ('date_demande', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True, verbose_name='référence du versement')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='users.profillivreur', verbose_name='livreur')),
            ],
            options={
                'verbose_name': 'Payout Livreur',
                'verbose_name_plural': 'Payouts Livreurs',
                'ordering': ['-date_demande'],
            },
        ),
    ]
