# Generated by Django 5.2.17 on 2026-09-27 22:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_etablissement_date_debut_abonnement_and_more'),
        ('orders', '0001_initial'),
        ('payments', '0003_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_abonnement', to='catalog.etablissement', verbose_name='établissement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('COMMANDE_CLIENT', 'Commande Client'), ('ABONNEMENT_PRO', 'Abonnement PRO')], db_index=True, default='COMMANDE_CLIENT', max_length=30, verbose_name='type de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='orders.commande', verbose_name='commande'),
        ),
        migrations.CreateModel(
            name='AbonnementPro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, verbose_name="montant de l'abonnement (FCFA)")),
                ('date_debut', models.DateTimeField(verbose_name='date de début')),
                ('date_expiration', models.DateTimeField(db_index=True, verbose_name="date d'expiration")),
                ('statut', models.CharField(choices=[('PAYE', 'Payé / Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], db_index=True, default='PAYE', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_pro', to='catalog.etablissement', verbose_name='établissement')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnement_pro', to='payments.paiement', verbose_name='paiement associé')),
            ],
            options={
                'verbose_name': 'Abonnement PRO',
                'verbose_name_plural': 'Abonnements PRO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactureAbonnement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='numéro de facture')),
                ('nom_etablissement_snapshot', models.CharField(max_length=255, verbose_name='nom établissement (snapshot)')),
                ('type_etablissement_snapshot', models.CharField(max_length=50, verbose_name='type établissement (snapshot)')),
                ('nom_proprietaire_snapshot', models.CharField(max_length=255, verbose_name='nom propriétaire (snapshot)')),
                ('email_proprietaire_snapshot', models.CharField(max_length=255, verbose_name='email propriétaire (snapshot)')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, verbose_name='montant HT')),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, verbose_name='montant total (FCFA)')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="date d'émission")),
                ('abonnement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='payments.abonnementpro', verbose_name='abonnement associé')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_abonnement', to='catalog.etablissement', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'Facture Abonnement PRO',
                'verbose_name_plural': 'Factures Abonnements PRO',
                'ordering': ['-date_emission'],
            },
        ),
    ]
