# Generated by Django 5.2.17 on 2026-09-16 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(choices=[('CLIENT', 'Client'), ('RESTAURANT', 'Restaurant'), ('VENDEUR', 'Vendeur'), ('LIVREUR', 'Livreur'), ('ADMINISTRATEUR', 'Administrateur')], max_length=50, unique=True, verbose_name='nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adresse email')),
                ('numero_telephone', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='numéro de téléphone')),
                ('prenom', models.CharField(max_length=150, verbose_name='prénom')),
                ('nom', models.CharField(max_length=150, verbose_name='nom de famille')),
                ('est_actif', models.BooleanField(default=True, verbose_name='est actif')),
                ('est_verifie', models.BooleanField(default=False, verbose_name='est vérifié')),
                ('is_staff', models.BooleanField(default=False, verbose_name='statut équipe admin')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='dernière connexion')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProfilClient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_client', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Client',
                'verbose_name_plural': 'Profils Clients',
            },
        ),
        migrations.CreateModel(
            name='UtilisateurRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_attribution', models.DateTimeField(auto_now_add=True, verbose_name="date d'attribution")),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_lies', to='users.role', verbose_name='rôle')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_attribues', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Rôle Utilisateur',
                'verbose_name_plural': 'Rôles Utilisateurs',
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'role'), name='unique_utilisateur_role')],
            },
        ),
    ]
