# Generated by Django 5.2.17 on 2026-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilclient',
            name='adresse_principale',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='adresse principale'),
        ),
        migrations.AddField(
            model_name='profilclient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='profilclient',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='profilclient',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='profilclient',
            name='notifications_activees',
            field=models.BooleanField(default=True, verbose_name='notifications activées'),
        ),
        migrations.AddField(
            model_name='profilclient',
            name='photo_avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="photo d'avatar"),
        ),
    ]
