# Generated by Django 5.2.17 on 2026-09-17 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilclient_adresse_principale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilLivreur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut_verification', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut de vérification')),
                ('est_disponible', models.BooleanField(default=False, verbose_name='est disponible')),
                ('latitude_actuelle', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude actuelle')),
                ('longitude_actuelle', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude actuelle')),
                ('date_derniere_position', models.DateTimeField(blank=True, null=True, verbose_name='date dernière position')),
                ('type_vehicule', models.CharField(choices=[('MOTO', 'Moto'), ('VOITURE', 'Voiture'), ('VELO', 'Vélo'), ('AUTRE', 'Autre')], default='MOTO', max_length=20, verbose_name='type de véhicule')),
                ('marque', models.CharField(blank=True, default='', max_length=100, verbose_name='marque')),
                ('modele', models.CharField(blank=True, default='', max_length=100, verbose_name='modèle')),
                ('immatriculation', models.CharField(blank=True, default='', max_length=50, verbose_name='immatriculation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livreur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Livreur',
                'verbose_name_plural': 'Profils Livreurs',
            },
        ),
        migrations.CreateModel(
            name='DocumentLivreur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('PIECE_IDENTITE', "Pièce d'identité"), ('PERMIS_CONDUIRE', 'Permis de conduire'), ('CARTE_GRISE', 'Carte grise'), ('AUTRE', 'Autre')], max_length=30, verbose_name='type de document')),
                ('fichier_url_ou_reference', models.CharField(max_length=500, verbose_name='fichier URL ou référence')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('date_verification', models.DateTimeField(blank=True, null=True, verbose_name='date de vérification')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('profil_livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.profillivreur', verbose_name='profil livreur')),
            ],
            options={
                'verbose_name': 'Document Livreur',
                'verbose_name_plural': 'Documents Livreurs',
            },
        ),
    ]
