# Generated by Django 5.2.17 on 2026-09-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profillivreur_documentlivreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='mode_actif',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('LIVREUR', 'Livreur')], default='CLIENT', max_length=20, verbose_name='mode actif'),
        ),
    ]
