# Generated by Django 5.2.17 on 2026-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_utilisateur_mode_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='profillivreur',
            name='date_expiration_assurance',
            field=models.DateField(blank=True, null=True, verbose_name="date d'expiration assurance"),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='equipements_certifies',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='équipements certifiés'),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='numero_reversement',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='numéro de compte reversement'),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='photo_avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="photo d'avatar"),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='secteur_intervention',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="secteur d'intervention"),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='statut_assurance',
            field=models.CharField(blank=True, default='CONFORME', max_length=30, verbose_name="statut de l'assurance"),
        ),
        migrations.AddField(
            model_name='profillivreur',
            name='type_compte_reversement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='type de compte reversement'),
        ),
    ]
