# Generated by Django 5.2.17 on 2026-09-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profillivreur_date_expiration_assurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profillivreur',
            name='comptes_reversement',
            field=models.JSONField(blank=True, default=list, verbose_name='comptes de reversement'),
        ),
    ]
