# Generated by Django 5.2.17 on 2026-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profillivreur_comptes_reversement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilclient',
            name='photo_avatar',
            field=models.TextField(blank=True, null=True, verbose_name="photo d'avatar"),
        ),
    ]
