# Generated by Django 5.2.17 on 2026-09-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('AFFECTEE', 'Affectée'), ('ACCEPTEE', 'Acceptée'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=30, verbose_name='statut de la livraison')),
                ('token_qr', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='token QR Code')),
                ('code_validation', models.CharField(db_index=True, max_length=6, verbose_name='code de validation (6 chiffres)')),
                ('est_validee', models.BooleanField(default=False, verbose_name='est validée')),
                ('methode_validation', models.CharField(blank=True, choices=[('QR_CODE', 'Scan QR Code'), ('CODE_VALIDATION', 'Code de validation à 6 chiffres')], max_length=30, null=True, verbose_name='méthode de validation')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='orders.commande', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
