# Generated by Django 5.2.17 on 2026-09-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('users', '0003_profillivreur_documentlivreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='users.profillivreur', verbose_name='livreur'),
        ),
    ]
