# Generated by Django 5.2.17 on 2026-09-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_livraison_livreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='date_attribution',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'attribution"),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('AFFECTEE', 'Affectée'), ('ACCEPTEE', 'Acceptée'), ('ARRIVE_RESTAURANT', 'Arrivé au restaurant'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=30, verbose_name='statut de la livraison'),
        ),
    ]
