# Generated by Django 5.2.17 on 2026-09-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_livraison_date_attribution_alter_livraison_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='code_validation',
            field=models.CharField(db_index=True, max_length=4, verbose_name='code de validation (4 chiffres)'),
        ),
    ]
