# Generated by Django 5.2.17 on 2026-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_alter_livraison_code_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='phase_attribution',
            field=models.IntegerField(default=1, verbose_name="phase d'attribution"),
        ),
        migrations.AddField(
            model_name='livraison',
            name='propositions_livreurs',
            field=models.JSONField(blank=True, default=dict, verbose_name='propositions livreurs'),
        ),
    ]
