# Generated by Django 6.0.6 on 2026-09-30 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('search_count', models.IntegerField(default=0)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quota Recherche Chatbot IA',
                'verbose_name_plural': 'Quotas Recherches Chatbot IA',
            },
        ),
    ]
