# Generated by Django 5.2.17 on 2026-10-03 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('titre', models.CharField(default='Nouvelle conversation', max_length=255)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'Système')], default='USER', max_length=20)),
                ('type_message', models.CharField(choices=[('TEXT', 'Texte'), ('IMAGE', 'Image'), ('ACTION', 'Action'), ('PLANNING', 'Planning')], default='TEXT', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('user_text', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('data_payload', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
            options={
                'verbose_name': 'Message IA',
                'verbose_name_plural': 'Messages IA',
                'ordering': ['date_creation'],
            },
        ),
    ]
