# Generated by Django 5.2.17 on 2026-09-17 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_email', models.CharField(blank=True, default='', max_length=255, verbose_name='email administrateur')),
                ('action', models.CharField(max_length=255, verbose_name='action exécutée')),
                ('ressource', models.CharField(max_length=255, verbose_name='ressource ciblée')),
                ('resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='identifiant ressource')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('statut', models.CharField(choices=[('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('FAILED', 'Échec')], default='SUCCESS', max_length=20, verbose_name='statut')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='détails complémentaires')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage')),
                ('administrateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='administrateur')),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'ordering': ['-timestamp'],
            },
        ),
    ]
