# Generated by Django 5.2.17 on 2026-09-16 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('nom', models.CharField(max_length=150, verbose_name='nom de la catégorie')),
                ('icone', models.CharField(blank=True, default='', max_length=100, verbose_name='icône')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name="URL de l'image")),
                ('est_active', models.BooleanField(default=True, verbose_name='est active')),
                ('ordre', models.IntegerField(default=0, verbose_name="ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=200, verbose_name="nom de l'établissement")),
                ('type_etablissement', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('VENDEUR', 'Vendeur à domicile')], db_index=True, default='RESTAURANT', max_length=30, verbose_name="type d'établissement")),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL du logo')),
                ('couverture_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la photo de couverture')),
                ('slogan', models.CharField(blank=True, default='', max_length=255, verbose_name='slogan')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('adresse', models.CharField(max_length=255, verbose_name='adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='note moyenne')),
                ('nombre_avis', models.IntegerField(default=0, verbose_name="nombre d'avis")),
                ('statut', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé')], default='open', max_length=20, verbose_name='statut')),
                ('heure_fermeture', models.CharField(blank=True, default='23h30', max_length=50, verbose_name='heure de fermeture')),
                ('telephone', models.CharField(blank=True, default='', max_length=30, verbose_name='téléphone')),
                ('specialite', models.CharField(blank=True, default='', max_length=150, verbose_name='spécialité')),
                ('nombre_videos', models.IntegerField(default=0, verbose_name='nombre de vidéos')),
                ('est_verifie', models.BooleanField(default=False, verbose_name='est vérifié par AYYOU')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=200, verbose_name='nom du produit')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix de base (FCFA)')),
                ('image_url', models.URLField(max_length=500, verbose_name="URL de l'image principale")),
                ('images_galerie', models.JSONField(blank=True, default=list, verbose_name='images de la galerie')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='est disponible')),
                ('stock_disponible', models.IntegerField(default=100, verbose_name='stock général disponible')),
                ('stock_ayyou_reserve', models.IntegerField(default=50, verbose_name='stock alloué à AYYOU')),
                ('temps_preparation', models.CharField(default='20-25 min', max_length=50, verbose_name='temps de préparation')),
                ('nombre_likes', models.IntegerField(default=0, verbose_name='nombre de likes')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='catalog.categorie', verbose_name='catégorie')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='catalog.etablissement', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'Produit / Plat',
                'verbose_name_plural': 'Produits / Plats',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OptionProduit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_option', models.CharField(choices=[('SAUCE', 'Sauce'), ('SUPPLEMENT', 'Supplément')], default='SAUCE', max_length=20, verbose_name="type d'option")),
                ('titre', models.CharField(max_length=150, verbose_name='titre')),
                ('sous_titre', models.CharField(blank=True, default='', max_length=255, verbose_name='sous-titre')),
                ('surcout_prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='surcoût prix (FCFA)')),
                ('est_inclus', models.BooleanField(default=False, verbose_name='inclus par défaut')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'Option / Supplément Produit',
                'verbose_name_plural': 'Options / Suppléments Produit',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicationFeed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media_url', models.URLField(max_length=500, verbose_name='URL du média')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10, verbose_name='type de média')),
                ('duree_video', models.CharField(blank=True, default='', max_length=20, verbose_name='durée vidéo (ex: 2:30)')),
                ('max_duree_secondes', models.IntegerField(default=180, verbose_name='durée max en secondes')),
                ('nombre_likes', models.IntegerField(default=0, verbose_name='nombre de likes')),
                ('nombre_partages', models.IntegerField(default=0, verbose_name='nombre de partages')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='catalog.etablissement', verbose_name='établissement')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='catalog.produit', verbose_name='produit associé')),
            ],
            options={
                'verbose_name': 'Publication Feed',
                'verbose_name_plural': 'Publications Feed',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProduit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150, verbose_name='titre de la variante')),
                ('sous_titre', models.CharField(blank=True, default='', max_length=255, verbose_name='sous-titre / description')),
                ('surcout_prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='surcoût prix (FCFA)')),
                ('est_requis', models.BooleanField(default=False, verbose_name='sélection obligatoire')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalog.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'Variante de Produit',
                'verbose_name_plural': 'Variantes de Produit',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LikeProduit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_catalog', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalog.produit', verbose_name='produit')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalog.publicationfeed', verbose_name='publication feed')),
            ],
            options={
                'verbose_name': 'Like Produit / Publication',
                'verbose_name_plural': 'Likes Produits / Publications',
                'constraints': [models.UniqueConstraint(condition=models.Q(('produit__isnull', False)), fields=('utilisateur', 'produit'), name='unique_like_utilisateur_produit'), models.UniqueConstraint(condition=models.Q(('publication__isnull', False)), fields=('utilisateur', 'publication'), name='unique_like_utilisateur_publication')],
            },
        ),
    ]
