# Generated by Django 5.2.17 on 2026-09-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfeed',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID public Cloudinary'),
        ),
    ]
