# Generated by Django 5.2.17 on 2026-09-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_publicationfeed_cloudinary_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='statut_verification',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut de vérification'),
        ),
        migrations.CreateModel(
            name='DocumentEtablissement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('REGISTRE_COMMERCE', 'Registre de commerce / NINEA'), ('CERTIFICAT_HYGIENE', "Certificat d'hygiène"), ('CNI_GERANT', 'CNI du gérant'), ('AUTRE', 'Autre')], max_length=30, verbose_name='type de document')),
                ('fichier_url_ou_reference', models.CharField(max_length=500, verbose_name='fichier URL ou référence')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('date_verification', models.DateTimeField(blank=True, null=True, verbose_name='date de vérification')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.etablissement', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'Document Établissement',
                'verbose_name_plural': 'Documents Établissements',
            },
        ),
    ]
