# Generated by Django 5.2.17 on 2026-09-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_etablissement_statut_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='date_debut_abonnement',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de début d'abonnement"),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='date_expiration_abonnement',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date d'expiration d'abonnement"),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='statut_abonnement',
            field=models.CharField(choices=[('INACTIF', 'Inactif'), ('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('ACTIF', 'Actif'), ('EXPIRE', 'Expiré')], db_index=True, default='INACTIF', max_length=30, verbose_name="statut d'abonnement"),
        ),
    ]
