# Generated by Django 6.0.6 on 2026-10-04 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_etablissement_date_debut_abonnement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementEtablissement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to='catalog.etablissement', verbose_name='établissement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_etablissements', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement Établissement',
                'verbose_name_plural': 'Abonnements Établissements',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'etablissement'), name='unique_abonnement_utilisateur_etablissement')],
            },
        ),
    ]
