# Generated by Django 5.2.17 on 2026-10-01 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_etablissement_date_debut_abonnement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='ID de session feed')),
                ('event_type', models.CharField(choices=[('IMPRESSION', "Impression (Affichée à l'écran)"), ('PLAY', 'Début de lecture'), ('PAUSE', 'Mise en pause'), ('WATCH', 'Visionnage en cours (Heartbeat)'), ('COMPLETED', 'Visionnage complet (100%)'), ('SKIP', 'Zappe rapide (< 3s)'), ('LIKE', 'Like activé'), ('UNLIKE', 'Like retiré'), ('SHARE', 'Partage vidéo'), ('CART_ADD', 'Ajout au panier depuis vidéo'), ('DISH_CLICK', 'Clic fiche plat')], db_index=True, max_length=50, verbose_name="type d'événement")),
                ('watch_time_seconds', models.FloatField(default=0.0, verbose_name='temps de visionnage (secondes)')),
                ('video_duration_seconds', models.FloatField(default=0.0, verbose_name='durée totale vidéo (secondes)')),
                ('progress_percent', models.FloatField(default=0.0, verbose_name='pourcentage de progression (0-100)')),
                ('feed_position', models.IntegerField(default=0, verbose_name='position dans le feed')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées complémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_events', to='catalog.publicationfeed', verbose_name='publication feed')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_events', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Journal Télémétrie Vidéo',
                'verbose_name_plural': 'Journaux Télémétrie Vidéo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['publication', 'event_type'], name='telemetry_v_publica_f76cd1_idx'), models.Index(fields=['utilisateur', 'created_at'], name='telemetry_v_utilisa_f11bbc_idx'), models.Index(fields=['session_id'], name='telemetry_v_session_e5b36a_idx')],
            },
        ),
    ]
