# Generated by Django 5.2.17 on 2026-10-02 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_etablissement_date_debut_abonnement_and_more'),
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationShadowLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='ID de session')),
                ('model_version', models.CharField(db_index=True, default='v3', max_length=50, verbose_name='version du modèle')),
                ('predicted_score', models.FloatField(default=0.0, verbose_name='score prédit par le modèle')),
                ('predicted_rank', models.IntegerField(default=0, verbose_name='rang prédit par le modèle')),
                ('feed_position', models.IntegerField(default=0, verbose_name='position réelle dans le feed')),
                ('request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID unique de requête')),
                ('candidate_count', models.IntegerField(default=0, verbose_name='nombre de candidats dans le batch')),
                ('execution_time_ms', models.FloatField(default=0.0, verbose_name="temps d'exécution scoring (ms)")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage du scoring')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_recommendations', to='catalog.publicationfeed', verbose_name='publication feed')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Journal Shadow Recommandation',
                'verbose_name_plural': 'Journaux Shadow Recommandation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='telemetry_r_session_883b8e_idx'), models.Index(fields=['model_version', 'created_at'], name='telemetry_r_model_v_d43fa1_idx'), models.Index(fields=['publication', 'model_version'], name='telemetry_r_publica_c7d06b_idx')],
            },
        ),
    ]
