# Generated by Django 5.2.17 on 2026-10-02 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_etablissement_date_debut_abonnement_and_more'),
        ('telemetry', '0002_recommendationshadowlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationExperimentLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='ID de session')),
                ('experiment_group', models.CharField(choices=[('control', 'Groupe Contrôle (Chronologique)'), ('experiment', 'Groupe Expérimental (Scoré V3)')], db_index=True, max_length=20, verbose_name="groupe d'expérimentation")),
                ('recommendation_mode', models.CharField(db_index=True, max_length=50, verbose_name='mode de recommandation active')),
                ('model_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='version du modèle')),
                ('predicted_score', models.FloatField(blank=True, null=True, verbose_name='score prédit par le modèle')),
                ('predicted_rank', models.IntegerField(blank=True, null=True, verbose_name='rang prédit par le modèle')),
                ('feed_position', models.IntegerField(default=0, verbose_name='position finale affichée dans le feed')),
                ('fallback_used', models.BooleanField(db_index=True, default=False, verbose_name='fallback chronologique appliqué')),
                ('scoring_time_ms', models.FloatField(default=0.0, verbose_name="temps d'exécution du scoring (ms)")),
                ('request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID unique de requête')),
                ('candidate_count', models.IntegerField(default=0, verbose_name='nombre de candidats dans le batch')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="horodatage de l'événement")),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_recommendations', to='catalog.publicationfeed', verbose_name='publication feed')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Journal Expérimentation Recommandation',
                'verbose_name_plural': 'Journaux Expérimentation Recommandation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['experiment_group', 'created_at'], name='telemetry_r_experim_c7846a_idx'), models.Index(fields=['session_id', 'created_at'], name='telemetry_r_session_d9cb64_idx'), models.Index(fields=['fallback_used', 'created_at'], name='telemetry_r_fallbac_997155_idx')],
            },
        ),
    ]
