# Generated by Django 5.2.17 on 2026-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationOTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6, verbose_name='code OTP')),
                ('type_verification', models.CharField(choices=[('VERIFICATION_TELEPHONE', 'Vérification du numéro de téléphone'), ('REINITIALISATION_MOT_DE_PASSE', 'Réinitialisation du mot de passe')], default='VERIFICATION_TELEPHONE', max_length=50, verbose_name='type de vérification')),
                ('date_expiration', models.DateTimeField(verbose_name="date d'expiration")),
                ('nombre_tentatives', models.IntegerField(default=0, verbose_name='nombre de tentatives')),
                ('est_utilise', models.BooleanField(default=False, verbose_name='est utilisé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Vérification OTP',
                'verbose_name_plural': 'Vérifications OTP',
                'ordering': ['-date_creation'],
            },
        ),
    ]
