# Generated by Django 6.0.6 on 2026-09-19 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('AUTHENTICATION', 'Authentification / OTP'), ('ORDER', 'Commande'), ('DELIVERY', 'Livraison'), ('PRO_VALIDATION', 'Validation PRO'), ('SUBSCRIPTION', 'Abonnement PRO'), ('SYSTEM', 'Système')], db_index=True, default='SYSTEM', max_length=50, verbose_name='type de notification')),
                ('canal', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], db_index=True, default='IN_APP', max_length=30, verbose_name='canal de diffusion')),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('message', models.TextField(verbose_name='contenu / message')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec'), ('LU', 'Lue')], db_index=True, default='ENVOYEE', max_length=30, verbose_name="statut d'envoi")),
                ('est_lu', models.BooleanField(db_index=True, default=False, verbose_name='est lue')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='date de lecture')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50, verbose_name='type de référence métier')),
                ('reference_id', models.CharField(blank=True, default='', max_length=100, verbose_name='identifiant référence métier')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées complémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', 'est_lu'], name='notificatio_utilisa_c5cf54_idx'), models.Index(fields=['utilisateur', '-created_at'], name='notificatio_utilisa_0877c3_idx')],
            },
        ),
    ]
