# Generated by Django 6.0.6 on 2026-10-04 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('AUTHENTICATION', 'Authentification / OTP'), ('ORDER', 'Commande'), ('DELIVERY', 'Livraison'), ('PRO_VALIDATION', 'Validation PRO'), ('SUBSCRIPTION', 'Abonnement PRO'), ('SYSTEM', 'Système'), ('RAPPEL_REPAS_PLANIFIE', 'Rappel Repas Planifié'), ('PUBLICATION_VIDEO', 'Publication Vidéo')], db_index=True, default='SYSTEM', max_length=50, verbose_name='type de notification'),
        ),
        migrations.CreateModel(
            name='PushNotificationPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('push_rappels_planning', models.BooleanField(default=True, verbose_name='push rappels planning repas')),
                ('push_publications_video', models.BooleanField(default=True, verbose_name='push publications vidéos abonnements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_preferences', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences Notifications Push',
                'verbose_name_plural': 'Préférences Notifications Push',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(db_index=True, max_length=500, verbose_name='endpoint push VAPID')),
                ('p256dh', models.CharField(max_length=255, verbose_name='clé publique p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='secret auth')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='agent utilisateur / navigateur')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement Web Push',
                'verbose_name_plural': 'Abonnements Web Push',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'endpoint'), name='unique_push_subscription_endpoint')],
            },
        ),
    ]
